### ISSUE TITLE
Variant for early (vertical) rf modulator north american coco2s?

### ISSUE THREAD

**Issue by alitel** [RivenHexagon/CoCo2_Video#1]
Hi there! This is more a question than an issue -- is this project intended specifically for the later variants of the coco2 with the horizontally mounted RF modulator can? I have an earlier (vertical rf can) coco2 version, and was hoping to add composite and/or s-video. I very much like your consolidation of the work started by ACs 8 bit zone. I'm unsure if this pcb will work in my situation though?
Many thanks! A

**Comment by RivenHexagon** [comment]
Hey Alitel, the current printed circuit board layout is designed to fit the CoCo2 model with a horizontally mounted RF modulator case. However, the modification itself would also work on earlier CoCo2 versions that use the vertically mounted modulator box. The only differences are in the pinout and the PCB form factor.

The lines entering the vertical modulator box connect in the same way to the internal circuitry (primarily the MC1372) as they do in the horizontal version. You could use my PCB with the older board by adapting the pin assignments using jumper wires. A.C. provided a thorough reverse of the original schematics for both modulator variations. And I'd be happy to assist.

But your question actually inspired me to develop a layout specifically for CoCo2 models with horizontally mounted RF boxes, which I aim to complete by the end of the year. Unfortunately, I don’t have a CoCo2 with a horizontal RF box on hand, so I'll need to work out the dimensions somehow.
Best Riven

**Comment by alitel** [comment]
Hi Riven -- that's great news! I just today finished connecting my coco up to an rgb2hdmi which works a treat for clarity BUT I would still like to make use of your mod when you get it built so I can select "softer" outputs for games etc. (Plus, the mod looks very fun). Let me know if I can help out -- I can take my rf can off the board and pull it apart and provide dimensions and layout pics etc. if you like.
Cheers! A

**Comment by RivenHexagon** [comment]
Perfect, I think the best would be to contact me on Discord (Riven Hexagon). I"ve checked out some pictures of your CoCo Model and figured the dimensions needed. I'd send you a drawing that indicates where to take them. Looking forward!

**Comment by RivenHexagon** [comment]
I have added an eMail address. You can contact me under RivenHexagon@posteo.de
